crud_movie/crud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

crud_movie/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/delete', views.delete, name='delete'),
    path('<int:movie_pk>/scores_create', views.scores_create, name='scores_create')
]

crud_movie/movies/models.py
from django.db import models

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.id}-{self.name}'


class Movie(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()

    def __str__(self):
        return f'{self.id}-{self.title}:{self.description}, {self.audience}'


class Score(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    score = models.IntegerField()

    def __str__(self):
        return f'{self.id}-{self.content}'

crud_movie/movies/views.py
from django.shortcuts import render,redirect
from .models import Genre, Movie, Score
# Create your views here.


def index(request):
    movies = Movie.objects.all()
    print(movies)
    #print(movies)
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.audience = format(movie.audience, ',')
    scores = movie.score_set.order_by('-pk')
    context = {
        'movie': movie,
        'scores': scores,
    }
    return render(request, 'movies/detail.html', context)


def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')

    else:
        return redirect('movies:detail', movie_pk)


def scores_create(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        score = request.POST.get('score')
        # 댓글 생성 및 저장
        value = Score(movie=movie, content=content, score=score)
        value.save()

        return redirect('movies:detail', movie_pk)

crud_movie/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
        <div class="col-sm-2">
            <br>
            <a href="{% url 'movies:index' %}">MAIN</a>
        </div>
        <div class="col-sm-8">
        {% block content %} {% endblock %}
        </div>
        <div class="col-sm-2"></div>

        </div>


    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

crud_movie/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block content%}

<h2>{{ movie.title }}</h2>
<p>관객수: {{ movie.audience }}명 </p>
<p>장르아이디: {{ movie.genre.name}}</p>
<p>{{ movie.description }}</p>
<img src="{{ movie.poster_url }}" alt="movie_img" width="240" height="360">
<hr>
<!--평점 출력-->
<p>{{ scores | length }} 개의 감상평 </p>
{% for score in scores %}
    <li>
        <ol>감상평 : {{ score.content }}</ol>
        <ol>평점 : {{ score.score }}</ol>


    </li>
    {% empty %}
    <p><b>평가가 없어요..</b></p>
{% endfor %}


<!--평점 입력-->
<form action="{% url 'movies:scores_create' movie.pk %}" method="post">
    {% csrf_token %}
    <label for="content">Comment</label>
    <textarea name="content" cols="60" rows="2" id="content" ></textarea>

    <label for="score">Score</label>
    <input type="number" name="score" id="score" min="0" max="10" step="0.5">
    <input type="submit" value="submit">
</form>

<hr>
<form action="{% url 'movies:delete' movie.pk %}" method="POST" style="display:inline" onsubmit="return confirm('R U SURE?')">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>


{% endblock %}

crud_movie/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block content %}


   <h1>메인 페이지</h1>
        <hr>
        {% for movie in movies %}
        <h2>{{ movie.title }}</h2>
        <img src="{{ movie.poster_url }}" alt="movie_img" width="240" height="360">
        <a href="{% url 'movies:detail' movie.pk %}">자세히 보기 </a>
        <br>
        <br>
        <hr>

        {% endfor %}

{% endblock %}