crud_exercise/movies/urls.py
from django.urls import path, include
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update')
]

crud_exercise/movies/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    title = models.TextField()
    title_en = models.TextField()
    audience = models.IntegerField()
    open_date = models.DateTimeField(auto_now_add=True)
    genre = models.TextField()
    watch_grade = models.TextField()
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

    def __str__(self):
        return f'{self.id}글 : {self.title}'

crud_exercise/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie


# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def new(request):
    return render(request, 'movies/new.html')


def create(request):
    title =request.POST.get('title')
    title_en = request.POST.get('title_en')
    audience = request.POST.get('audience')
    open_date = request.POST.get('open_date')
    genre = request.POST.get('genre')
    watch_grade = request.POST.get('watch_grade')
    score = request.POST.get('score')
    poster_url = request.POST.get('poster_url')
    description = request.POST.get('description')
    movie = Movie(title=title, title_en=title_en, audience=audience,
                  open_date=open_date, genre=genre, watch_grade=watch_grade,
                  score=score, poster_url=poster_url, description=description,
                  )
    movie.save()

    return redirect('movies:index')


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie.pk)


def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title_en')
        movie.audience = request.POST.get('audience')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch_grade')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')

        movie.save()

        return redirect('movies:detail', movie.pk)

    else:
        context = {
            'movie': movie,
        }
        return render(request, 'movies/update.html', context)

crud_exercise/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

crud_exercise/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block content %}

<h1>DETAIL 페이지</h1>

<h2>{{ movie.title }}</h2>
<p>{{ movie.title_en }}</p>
<p>{{ movie.audience }}</p>
<p>{{ movie.open_date }}</p>
<p>{{ movie.genre }}</p>
<p>{{ movie.watch_grade }}</p>
<p>{{ movie.score }}</p>
<p>{{ movie.description }}</p>
<img src="{{ movie.poster_url }}" alt="movie_img" width="480" height="600">

<form action="{% url 'movies:delete' movie.pk %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE??')">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
<a href="{% url 'movies:update' movie.pk %}">수정</a>
<a href="{% url 'movies:index' %}">메인 페이지</a>
<hr>





{% endblock %}

crud_exercise/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block content %}
<br>
<h1>test 페이지입니다.</h1><br>
<a href="{% url 'movies:new' %}">영화 작성</a>
<hr>
{% for movie in movies %}
<p>{{ movie.title }} </p>
<p>{{ movie.title_en }} </p>
<p>{{ movie.audience }} </p>
<p>{{ movie.open_date }} </p>
<p>{{ movie.genre }} </p>
<p>{{ movie.watch_grade }} </p>
<p>{{ movie.score }} </p>
<img src="{{ movie.poster_url }}" alt="movie_img" width="480px" height="680px">
<p>{{ movie.description }} </p>
<br>
<a href="{% url 'movies:detail' movie.pk %}">자세히 보기</a>
<hr>

{% endfor%}
{% endblock %}

crud_exercise/movies/templates/movies/new.html
{% extends 'movies/base.html' %}
{% block content %}
<br>
<h1>new 영화 입력 페이지입니다.</h1><br>
<form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
<label for="title">TITLE</label>
<input type="text" name="title" id="title"><br>
<label for="title_en">TITLE_EN</label>
<input type="text" name="title_en" id="title_en"><br>
<label for="audience">AUDIENCE</label>
<input type="text" name="audience" id="audience"><br>


<label for="genre">GENRE</label>
<input type="text" name="genre" id="genre"><br>
<label for="watch_grade">WATCH_GRADE</label>
<input type="text" name="watch_grade" id="watch_grade"><br>
<label for="score">SCORE</label>
<input type="text" name="score" id="score"><br>
<label for="open_date">OPEN_DATE</label>
<input type="date" name="open_date" id="open_date"><br>
<label for="open_date"></label>

<label for="poster_url">POSTER_URL</label>
<input type="text" name="poster_url" id="poster_url"><br>

<label for="description">DESCRIPTION</label>
<input type="text" name="description" id="description"><br>


<input type="submit" value="제출">
</form>

<hr>

{% endblock %}

crud_exercise/movies/templates/movies/update.html
{% extends 'movies/base.html' %}
{% block content %}
<br>
<h1>update 영화 입력 페이지입니다.</h1><br>
<form action="" method="POST">
    {% csrf_token %}
<label for="title">TITLE</label>
<input type="text" name="title" id="title" value="{{movie.title}}"><br>
<label for="title_en">TITLE_EN</label>
<input type="text" name="title_en" id="title_en" value="{{movie.title_en}}"><br>
<label for="audience">AUDIENCE</label>
<input type="text" name="audience" id="audience" value="{{movie.audience}}"><br>


<label for="genre">GENRE</label>
<input type="text" name="genre" id="genre" value="{{movie.genre}}"><br>
<label for="watch_grade">WATCH_GRADE</label>
<input type="text" name="watch_grade" id="watch_grade" value="{{movie.watch_grade}}"><br>
<label for="score">SCORE</label>
<input type="text" name="score" id="score" value="{{movie.score}}"><br>
<label for="open_date">OPEN_DATE</label>
<input type="date" name="open_date" id="open_date" value="{{movie.open_date}}"><br>
<label for="open_date"></label>
    <label for="poster_url">POSTER_URL</label>
<input type="text" name="poster_url" id="poster_url" value="{{movie.poster_url}}"><br>
<label for="description">DESCRIPTION</label>
<input type="text" name="description" id="description" value="{{movie.description}}"><br>
    <input type="submit" value="제출">
</form>

<hr>

{% endblock %}